apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dpschool-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: dpschool-deployment
      labels:
        app: dpschool-pod
    spec:
      containers:
      - image: registry.eu-de.bluemix.net/digital_product_school/dpschool-react:wip
        name: dpschool-pod
        ports:
          - containerPort: 5000
            name: http
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          successThreshold: 2
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: dpschool-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    nodePort: 30500
  selector:
    app: dpschool-pod